#!/bin/bash
set -e

# DMA Migration Analyzer for GitLab CI
# Usage: ./dma-analyzer.sh <migration-path> [options]

MIGRATION_PATH="${1:-migrations/}"
DB_TYPE="${DMA_DB_TYPE:-postgresql}"
DB_URL="${DMA_DB_URL:-}"
FAIL_ON_RISK="${DMA_FAIL_ON_RISK:-}"
COMPREHENSIVE="${DMA_COMPREHENSIVE:-true}"

echo "🔍 DMA Migration Analysis"
echo "========================="
echo "Migration Path: $MIGRATION_PATH"
echo "Database Type: $DB_TYPE"
echo ""

# Install DMA
echo "Installing DMA..."
go install github.com/iamsr/dma/cmd/dma@latest

# Build command
CMD="dma analyze $MIGRATION_PATH --format json --db-type $DB_TYPE"

if [ -n "$DB_URL" ]; then
  CMD="$CMD --db $DB_URL"
else
  CMD="$CMD --dry-run"
fi

if [ "$COMPREHENSIVE" = "true" ]; then
  CMD="$CMD --comprehensive"
fi

if [ -n "$FAIL_ON_RISK" ]; then
  CMD="$CMD --fail-on-risk-level $FAIL_ON_RISK"
fi

# Run analysis
echo "Running analysis..."
OUTPUT=$(eval $CMD)

# Save to file
echo "$OUTPUT" > dma-report.json

# Parse and display summary
echo ""
echo "📊 Analysis Results"
echo "==================="

TOTAL_OPS=$(echo "$OUTPUT" | jq '[.Migrations[].Operations] | flatten | length')
HIGH_RISK=$(echo "$OUTPUT" | jq '[.Migrations[].Operations] | flatten | map(select(.RiskScore >= 51)) | length')

echo "Total Operations: $TOTAL_OPS"
echo "High Risk Operations: $HIGH_RISK"

if [ "$HIGH_RISK" -gt 0 ]; then
  echo ""
  echo "⚠️  High Risk Operations Found:"
  echo "$OUTPUT" | jq -r '
    [.Migrations[].Operations] | flatten | 
    map(select(.RiskScore >= 51)) | 
    .[] | 
    "  • \(.Type) on \(.TableName) (Risk: \(.RiskScore))"
  '
fi

# Generate Markdown report
cat > dma-report.md <<EOF
# 🔍 Migration Analysis Report

**Total Operations:** $TOTAL_OPS  
**High Risk Operations:** $HIGH_RISK

## Operations

$(echo "$OUTPUT" | jq -r '
  [.Migrations[].Operations] | flatten | 
  .[] | 
  "| \(.Type) | \(.TableName // "N/A") | \(.RiskScore) | \(.LockType) | \(.EstimatedTimeSeconds)s |"
' | awk 'BEGIN {
  print "| Operation | Table | Risk | Lock Type | Time |"
  print "|-----------|-------|------|-----------|------|"
} {print}')

---
🤖 Generated by [DMA](https://github.com/iamsr/dma)
EOF

echo ""
echo "✅ Analysis complete!"
echo "Reports saved:"
echo "  - dma-report.json"
echo "  - dma-report.md"

# Exit with error if risk threshold exceeded
if [ -n "$FAIL_ON_RISK" ]; then
  MAX_RISK=$(echo "$OUTPUT" | jq -r '[.Migrations[].Operations] | flatten | map(.RiskScore) | max')
  THRESHOLD_MAP='{"low":25,"medium":50,"high":75,"critical":100}'
  THRESHOLD=$(echo "$THRESHOLD_MAP" | jq -r ".[\"$FAIL_ON_RISK\"]")
  
  if [ "$MAX_RISK" -gt "$THRESHOLD" ]; then
    echo ""
    echo "❌ Risk threshold exceeded!"
    exit 1
  fi
fi
