import * as github from '@actions/github';
import * as core from '@actions/core';
import { AnalysisResult } from './analyzer';

export async function commentOnPR(
  token: string,
  result: AnalysisResult
): Promise<void> {
  const octokit = github.getOctokit(token);
  const context = github.context;

  if (!context.payload.pull_request) {
    core.info('Not a pull request, skipping comment');
    return;
  }

  const pr = context.payload.pull_request;
  const body = formatComment(result);

  // Check if comment already exists
  const { data: comments } = await octokit.rest.issues.listComments({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: pr.number,
  });

  const existingComment = comments.find((c) =>
    c.body?.includes('🔍 Migration Analysis Results')
  );

  if (existingComment) {
    // Update existing comment
    await octokit.rest.issues.updateComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      comment_id: existingComment.id,
      body,
    });
    core.info('Updated existing PR comment');
  } else {
    // Create new comment
    await octokit.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: pr.number,
      body,
    });
    core.info('Created new PR comment');
  }
}

function formatComment(result: AnalysisResult): string {
  let comment = result.summary + '\n\n';

  // Add recommendations for high-risk operations
  const highRiskOps = [];
  for (const migration of result.jsonOutput.Migrations) {
    for (const op of migration.Operations) {
      if (op.RiskScore >= 51) {
        highRiskOps.push(op);
      }
    }
  }

  if (highRiskOps.length > 0) {
    comment += '### ⚠️ High Risk Operations\n\n';
    for (const op of highRiskOps) {
      comment += `**${op.Type} on \`${op.TableName}\`** (Risk: ${op.RiskScore})\n`;
      if (op.Recommendations && op.Recommendations.length > 0) {
        comment += 'Recommendations:\n';
        for (const rec of op.Recommendations) {
          comment += `- ${rec}\n`;
        }
      }
      comment += '\n';
    }
  }

  // Add alternatives if available
  const opsWithAlternatives = [];
  for (const migration of result.jsonOutput.Migrations) {
    for (const op of migration.Operations) {
      if (op.Alternatives && op.Alternatives.length > 0) {
        opsWithAlternatives.push(op);
      }
    }
  }

  if (opsWithAlternatives.length > 0) {
    comment += '### 💡 Safer Alternatives Available\n\n';
    for (const op of opsWithAlternatives) {
      comment += `**${op.Type} on \`${op.TableName}\`**\n`;
      for (const alt of op.Alternatives) {
        comment += `- ${alt.StrategyName}: ${alt.Description}\n`;
      }
      comment += '\n';
    }
  }

  comment += '\n---\n';
  comment += `🤖 Generated by [DMA](https://github.com/iamsr/tapa)`;

  return comment;
}
